# run: conda env create -f environment.yml
# run: conda env update -f environment.yml
# run: conda env remove -n cellprofiler
name: cellprofiler
# in order of priority: lowest (top) to highest (bottom)
channels:
  - goodman # mysql-python for mac
  - bioconda
  - cyclus # java-jdk for windows
  - conda-forge # libxml2 for windows
dependencies:
  - python=2.7
  - jupyter
  - ipywidgets
  - matplotlib<2
  - wxpython
  - lxml
  - libxml2
  - libxslt
  - cython
  - mysql-python
  - mahotas
  - tifffile
  - numpy
  - scipy
  - pyzmq
  - h5py
  - java-jdk
  - pillow
  - javabridge
  - pip
  - pip:
    - python-bioformats
    - centrosome
    - prokaryote
    - cellh5
    - inflect
    - "--editable=git+https://github.com/scikit-image/scikit-image.git@c8918053ce34b9402a90be61b13ecabf541e90ee#egg=scikit-image-0.13.0dev"